import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import TopBar from "@/components/common/TopBar";
import BrandHeader from "@/components/common/BrandHeader";
import Navigation from "@/components/common/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from 'react-hot-toast';
import ReduxProvider from "../redux/ReduxProvider";
import MainLayout from "@/components/common/MainLayout";
import Footer from "@/components/common/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Toaster position="top-right" />
          <Provider>
            <TopBar />
            <BrandHeader />
            <Navigation />
            <MainLayout>
              {children}
            </MainLayout>
            <Footer />
          </Provider>
        </ReduxProvider>
      </body>
    </html>
  );
}
